# Generated by Django 5.0.3 on 2024-03-27 23:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id_denuncia', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('denunciaType', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('denuncia', models.CharField(max_length=1000)),
                ('data', models.CharField(max_length=10)),
            ],
        ),
    ]
