# Generated by Django 5.0.3 on 2024-05-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Denuncia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='numero',
            field=models.CharField(max_length=10),
        ),
    ]
