# Generated by Django 5.0.3 on 2024-05-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Denuncia', '0002_alter_denuncia_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='imagem',
            field=models.ImageField(null=True, upload_to='imagens', verbose_name='Foto da denúncia'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='numero',
            field=models.CharField(max_length=5),
        ),
    ]
