# Generated by Django 5.0.3 on 2024-05-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Denuncia', '0003_denuncia_imagem_alter_denuncia_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='imagem',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
