# Generated by Django 5.0.3 on 2024-05-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Denuncia', '0004_remove_denuncia_imagem_denuncia_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denuncia',
            old_name='image_url',
            new_name='imagem',
        ),
    ]
